# Generated by Django 4.2.8 on 2026-03-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
