# Generated by Codex on 2026-03-28

from django.conf import settings
from django.db import migrations


def backfill_user_profiles(apps, schema_editor):
    user_model = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    user_profile_model = apps.get_model("tasks", "UserProfile")

    existing_user_ids = set(user_profile_model.objects.values_list("user_id", flat=True))
    missing_profiles = [
        user_profile_model(user_id=user.id)
        for user in user_model.objects.all()
        if user.id not in existing_user_ids
    ]

    if missing_profiles:
        user_profile_model.objects.bulk_create(missing_profiles)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0006_task_assignee"),
    ]

    operations = [
        migrations.RunPython(backfill_user_profiles, migrations.RunPython.noop),
    ]
