# Generated by Django 4.2.8 on 2026-04-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_backfill_user_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this admin is approved.'),
        ),
    ]
